### ISSUE TITLE
Прогнозирование рейтинга фильмов

### ISSUE THREAD

**Issue by Ghostyra** [pro100olga/movie_rating_prediction#1]
Добрый день, наткнулся на ваше исследование возможности прогнозирования рейтинга фильмов. Правда, не могу в полной мер исследовать код, так как отсутствуют данные по Оскарам, который вы получили с помощью парсинга. Не могли ли вы поделиться данными csv-шками?

**Comment by pro100olga** [comment]
Конечно, добавила файлы в общую папку: https://github.com/pro100olga/movie_rating_prediction

**Comment by Ghostyra** [comment]
Немного с запозданием, но благодарю!02.05.2020, 18:42, "Olga Makarova" <notifications@github.com>:
Конечно, добавила файлы в общую папку: https://github.com/pro100olga/movie_rating_prediction
